// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3HS_GDxY6zSNNJw5Sjw3keGyN2hkvp4c',
    appId: '1:276652156629:web:e90e4337cff335309ca45c',
    messagingSenderId: '276652156629',
    projectId: 'spotify-flutter-clone',
    authDomain: 'spotify-flutter-clone.firebaseapp.com',
    storageBucket: 'spotify-flutter-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4-sADygB88xUk24lnft5FMRSN1t4rPKM',
    appId: '1:276652156629:android:437198f75a975e0d9ca45c',
    messagingSenderId: '276652156629',
    projectId: 'spotify-flutter-clone',
    storageBucket: 'spotify-flutter-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdeggQtkV0sIRXH6J2TAXCDVqQZBSWK_w',
    appId: '1:276652156629:ios:22aff8d668d94f739ca45c',
    messagingSenderId: '276652156629',
    projectId: 'spotify-flutter-clone',
    storageBucket: 'spotify-flutter-clone.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdeggQtkV0sIRXH6J2TAXCDVqQZBSWK_w',
    appId: '1:276652156629:ios:22aff8d668d94f739ca45c',
    messagingSenderId: '276652156629',
    projectId: 'spotify-flutter-clone',
    storageBucket: 'spotify-flutter-clone.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3HS_GDxY6zSNNJw5Sjw3keGyN2hkvp4c',
    appId: '1:276652156629:web:b6c85ed60a8454aa9ca45c',
    messagingSenderId: '276652156629',
    projectId: 'spotify-flutter-clone',
    authDomain: 'spotify-flutter-clone.firebaseapp.com',
    storageBucket: 'spotify-flutter-clone.appspot.com',
  );
}
